apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-deployment
spec:
  replicas: 5

  selector:
    matchLabels:
      app: myapp
      version: stable

  template:
    metadata:
      labels:
        app: myapp
        version: stable
    spec:
      containers:
        - name: stable-container
          image: nginx
          ports:
            - containerPort: 80