apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-vol
spec:
  containers:
  - name: myapp
    image: nginx
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret
  volumes:
  - name: secret-volume
    secret:
      secretName: myapp-secret