apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-deployment
spec:
  replicas: 3

  selector:
    matchLabels:
      app: myapp
      version: a

  template:
    metadata:
      labels:
        app: myapp
        version: a
    spec:
      containers:
        - name: a-container
          image: nginx
          ports:
            - containerPort: 80