apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-west-2c
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-volume
      mountPath: /mnt/data
  volumes:
  - name: nginx-volume
    persistentVolumeClaim:
      claimName: nginx-pvc-static