apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-static
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: nginx-pv
  storageClassName: ""