apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  fsType: ext4

# eksctl create addon --cluster demo-eks --name aws-ebs-csi-driver --region us-west-2 --force