apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
spec:
  replicas: 3

  selector:
    matchLabels:
      app: myapp 
      
  template:
    metadata:
      labels:
        app: myapp 
        version: green
    spec:
      containers:
        - name: green-container
          image: ishika979/super-mario:latest
          ports:
            - containerPort: 80